# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('page_id', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=300)),
                ('street', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('pin', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-likes'],
            },
        ),
    ]
